import { mutation, query } from "../_generated/server";
import { v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import { Id } from "../_generated/dataModel";
import { api } from "../_generated/api";

const sectionTypeValidator = v.union(
  v.literal("topSellers"),
  v.literal("itemsOnPromotion"),
  v.literal("shopByCategory"),
  v.literal("promoBanner"),
  v.literal("featuredBrands"),
);

// ── Queries ───────────────────────────────────────────────────────────────────

/**
 * Get a homepage section by type. Returns null if not configured yet.
 */
export const getSection = query({
  args: { sectionType: sectionTypeValidator },
  returns: v.union(
    v.object({
      _id: v.id("homepageSection"),
      _creationTime: v.number(),
      sectionType: sectionTypeValidator,
      productIds: v.optional(v.array(v.id("products"))),
      categoryIds: v.optional(v.array(v.id("productCategory"))),
      isAutoGenerated: v.boolean(),
      lastModifiedBy: v.optional(v.id("users")),
      lastModifiedAt: v.optional(v.number()),
    }),
    v.null(),
  ),
  handler: async (ctx, args) => {
    return await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", args.sectionType))
      .unique();
  },
});

/**
 * List all eligible (non-medicine, non-prescription, non-deleted) products
 * for the admin to pick from when configuring homepage sections.
 * Enriches each product with its brand name for display in the admin UI.
 */
export const listEligibleProducts = query({
  args: {},
  returns: v.array(v.any()),
  handler: async (ctx) => {
    const products = await ctx.db
      .query("products")
      .withIndex("by_isDeleted_and_name", (q) => q.eq("isDeleted", undefined))
      .collect();

    const eligible = products.filter(
      (p) => !p.isMedicine && !p.isPrescriptionControlled,
    );

    // Enrich with brand names
    const enriched = await Promise.all(
      eligible.map(async (p) => {
        let brandName: string | null = null;
        if (p.brandId) {
          const brand = await ctx.db.get(p.brandId);
          brandName = brand?.name ?? null;
        }
        return { ...p, brandName };
      }),
    );

    return enriched;
  },
});

/**
 * List all non-deleted product categories for category selection.
 */
export const listEligibleCategories = query({
  args: {},
  returns: v.array(v.any()),
  handler: async (ctx) => {
    return await ctx.db
      .query("productCategory")
      .withIndex("by_isDeleted_and_name", (q) => q.eq("isDeleted", undefined))
      .collect();
  },
});

// ── Mutations ─────────────────────────────────────────────────────────────────

/**
 * Save (create or update) a homepage section with manually chosen items.
 * Validates that no medicine or prescription-controlled products are included.
 */
export const saveSection = mutation({
  args: {
    sectionType: sectionTypeValidator,
    productIds: v.optional(v.array(v.id("products"))),
    categoryIds: v.optional(v.array(v.id("productCategory"))),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    // Validate products are not medicine / prescription-controlled
    if (args.productIds) {
      for (const productId of args.productIds) {
        const product = await ctx.db.get(productId);
        if (!product) throw new Error(`Product ${productId} not found`);
        if (product.isMedicine || product.isPrescriptionControlled) {
          throw new Error(
            `Product "${product.name}" is medicine or prescription-controlled and cannot be displayed in homepage sections`,
          );
        }
        if (product.isDeleted) {
          throw new Error(
            `Product "${product.name}" has been deleted and cannot be displayed`,
          );
        }
      }
    }

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", args.sectionType))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        productIds: args.productIds,
        categoryIds: args.categoryIds,
        isAutoGenerated: false,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    } else {
      await ctx.db.insert("homepageSection", {
        sectionType: args.sectionType,
        productIds: args.productIds,
        categoryIds: args.categoryIds,
        isAutoGenerated: false,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    }
    return null;
  },
});

/**
 * Reset "Top Sellers" to auto-select:
 * - Non-medicine, non-prescription products sorted by purchaseCount DESC.
 * - Takes the top 12 products.
 */
export const resetTopSellers = mutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    // Get all non-deleted products sorted by purchaseCount descending
    const products = await ctx.db
      .query("products")
      .withIndex("by_isDeleted_and_purchaseCount", (q) =>
        q.eq("isDeleted", undefined),
      )
      .order("desc")
      .collect();

    const eligible = products
      .filter((p) => !p.isMedicine && !p.isPrescriptionControlled)
      .slice(0, 12);

    const productIds: Array<Id<"products">> = eligible.map((p) => p._id);

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "topSellers"))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        productIds,
        isAutoGenerated: true,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    } else {
      await ctx.db.insert("homepageSection", {
        sectionType: "topSellers",
        productIds,
        isAutoGenerated: true,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    }
    return null;
  },
});

/**
 * Reset "Items on Promotion" to auto-select:
 * - Non-medicine, non-prescription products that have a promotionPriceInUSDCents.
 * - Sorted by purchaseCount DESC.
 * - Takes the top 12 products.
 */
export const resetItemsOnPromotion = mutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    // Get all non-deleted products that have a promotion price
    const products = await ctx.db
      .query("products")
      .withIndex("by_isDeleted_and_promotionPrice", (q) =>
        q.eq("isDeleted", undefined),
      )
      .order("desc")
      .collect();

    const eligible = products
      .filter(
        (p) =>
          !p.isMedicine &&
          !p.isPrescriptionControlled &&
          p.promotionPriceInUSDCents !== undefined,
      )
      // Sort by purchaseCount descending
      .sort((a, b) => (b.purchaseCount ?? 0) - (a.purchaseCount ?? 0))
      .slice(0, 12);

    const productIds: Array<Id<"products">> = eligible.map((p) => p._id);

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) =>
        q.eq("sectionType", "itemsOnPromotion"),
      )
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        productIds,
        isAutoGenerated: true,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    } else {
      await ctx.db.insert("homepageSection", {
        sectionType: "itemsOnPromotion",
        productIds,
        isAutoGenerated: true,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    }
    return null;
  },
});

/**
 * Reset "Shop by Category" to auto-select:
 * - Unique categories from the products with the highest purchaseCount.
 * - Excludes categories that only contain medicine/prescription products.
 * - Takes up to 8 categories.
 */
export const resetShopByCategory = mutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    // Get all non-deleted, non-medicine products sorted by purchaseCount desc
    const products = await ctx.db
      .query("products")
      .withIndex("by_isDeleted_and_purchaseCount", (q) =>
        q.eq("isDeleted", undefined),
      )
      .order("desc")
      .collect();

    const eligibleProducts = products.filter(
      (p) => !p.isMedicine && !p.isPrescriptionControlled,
    );

    // Collect unique category IDs in order of first appearance
    // (products are already sorted by purchaseCount desc)
    const seenCategoryIds = new Set<string>();
    const orderedCategoryIds: Array<Id<"productCategory">> = [];

    for (const product of eligibleProducts) {
      if (!product.productCategoryIds) continue;
      for (const catId of product.productCategoryIds) {
        if (!seenCategoryIds.has(catId)) {
          seenCategoryIds.add(catId);
          orderedCategoryIds.push(catId);
        }
      }
      if (orderedCategoryIds.length >= 8) break;
    }

    // Verify categories exist and are not deleted
    const validCategoryIds: Array<Id<"productCategory">> = [];
    for (const catId of orderedCategoryIds.slice(0, 8)) {
      const cat = await ctx.db.get(catId);
      if (cat && !cat.isDeleted) {
        validCategoryIds.push(catId);
      }
    }

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "shopByCategory"))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        categoryIds: validCategoryIds,
        isAutoGenerated: true,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    } else {
      await ctx.db.insert("homepageSection", {
        sectionType: "shopByCategory",
        categoryIds: validCategoryIds,
        isAutoGenerated: true,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    }
    return null;
  },
});

/**
 * Get the promo banner configuration (image, texts, link).
 */
export const getPromoBanner = query({
  args: {},
  returns: v.union(
    v.object({
      _id: v.id("homepageSection"),
      _creationTime: v.number(),
      storageId: v.optional(v.id("_storage")),
      cdnImageUrl: v.optional(v.string()),
      cdnImageKey: v.optional(v.string()),
      badgeText: v.optional(v.string()),
      headlineText: v.optional(v.string()),
      buttonText: v.optional(v.string()),
      buttonLink: v.optional(v.string()),
      lastModifiedBy: v.optional(v.id("users")),
      lastModifiedAt: v.optional(v.number()),
    }),
    v.null(),
  ),
  handler: async (ctx, args) => {
    const section = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "promoBanner"))
      .unique();

    if (!section) return null;
    return {
      _id: section._id,
      _creationTime: section._creationTime,
      storageId: section.storageId,
      cdnImageUrl: section.cdnImageUrl,
      cdnImageKey: section.cdnImageKey,
      badgeText: section.badgeText,
      headlineText: section.headlineText,
      buttonText: section.buttonText,
      buttonLink: section.buttonLink,
      lastModifiedBy: section.lastModifiedBy,
      lastModifiedAt: section.lastModifiedAt,
    };
  },
});

/**
 * Save the promo banner configuration (image, texts, link).
 */
export const savePromoBanner = mutation({
  args: {
    storageId: v.optional(v.id("_storage")),
    cdnImageUrl: v.optional(v.string()),
    cdnImageKey: v.optional(v.string()),
    badgeText: v.optional(v.string()),
    headlineText: v.optional(v.string()),
    buttonText: v.optional(v.string()),
    buttonLink: v.optional(v.string()),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "promoBanner"))
      .unique();

    if (existing) {
      // Delete old CDN image if it changed
      if (existing.cdnImageKey && existing.cdnImageKey !== args.cdnImageKey) {
        await ctx.scheduler.runAfter(0, api.cdn.deleteFile, {
          key: existing.cdnImageKey,
        });
      }

      await ctx.db.patch(existing._id, {
        storageId: args.storageId,
        cdnImageUrl: args.cdnImageUrl,
        cdnImageKey: args.cdnImageKey,
        badgeText: args.badgeText,
        headlineText: args.headlineText,
        buttonText: args.buttonText,
        buttonLink: args.buttonLink,
        isAutoGenerated: false,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    } else {
      await ctx.db.insert("homepageSection", {
        sectionType: "promoBanner",
        isAutoGenerated: false,
        storageId: args.storageId,
        cdnImageUrl: args.cdnImageUrl,
        cdnImageKey: args.cdnImageKey,
        badgeText: args.badgeText,
        headlineText: args.headlineText,
        buttonText: args.buttonText,
        buttonLink: args.buttonLink,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    }
    return null;
  },
});

/**
 * Clear (delete) the promo banner configuration entirely.
 */
export const clearPromoBanner = mutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "promoBanner"))
      .unique();

    if (existing) {
      if (existing.cdnImageKey) {
        await ctx.scheduler.runAfter(0, api.cdn.deleteFile, {
          key: existing.cdnImageKey,
        });
      }
      await ctx.db.delete(existing._id);
    }
    return null;
  },
});

/**
 * List all non-deleted brands for the admin to pick from when
 * configuring the Featured Brands homepage section.
 */
export const listEligibleBrands = query({
  args: {},
  returns: v.array(v.any()),
  handler: async (ctx) => {
    return await ctx.db
      .query("productBrand")
      .withIndex("by_isDeleted_and_name", (q) => q.eq("isDeleted", undefined))
      .collect();
  },
});

/**
 * Get the Featured Brands section configuration.
 * Returns null if not configured yet.
 */
export const getFeaturedBrandsSection = query({
  args: {},
  returns: v.union(
    v.object({
      _id: v.id("homepageSection"),
      _creationTime: v.number(),
      brandIds: v.optional(v.array(v.id("productBrand"))),
      isAutoGenerated: v.boolean(),
      lastModifiedBy: v.optional(v.id("users")),
      lastModifiedAt: v.optional(v.number()),
    }),
    v.null(),
  ),
  handler: async (ctx) => {
    const section = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "featuredBrands"))
      .unique();

    if (!section) return null;
    return {
      _id: section._id,
      _creationTime: section._creationTime,
      brandIds: section.brandIds,
      isAutoGenerated: section.isAutoGenerated,
      lastModifiedBy: section.lastModifiedBy,
      lastModifiedAt: section.lastModifiedAt,
    };
  },
});

/**
 * Save (create or update) the Featured Brands section with manually chosen brands.
 */
export const saveFeaturedBrands = mutation({
  args: {
    brandIds: v.array(v.id("productBrand")),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    // Validate each brand exists and is not deleted
    for (const brandId of args.brandIds) {
      const brand = await ctx.db.get(brandId);
      if (!brand) throw new Error(`Brand ${brandId} not found`);
      if (brand.isDeleted) {
        throw new Error(
          `Brand "${brand.name}" has been deleted and cannot be featured`,
        );
      }
    }

    const existing = await ctx.db
      .query("homepageSection")
      .withIndex("by_sectionType", (q) => q.eq("sectionType", "featuredBrands"))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        brandIds: args.brandIds,
        isAutoGenerated: false,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    } else {
      await ctx.db.insert("homepageSection", {
        sectionType: "featuredBrands",
        brandIds: args.brandIds,
        isAutoGenerated: false,
        lastModifiedBy: userId,
        lastModifiedAt: Date.now(),
      });
    }
    return null;
  },
});
